name: cd-weather-app

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: move files to dist/
      run: |
        mkdir dist
        cp index.html style.css app.js dist/

    - name: Execute SSH commands to resetfolder
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          mv /var/www/weather-app.hugo-vanhoutte.dev/dist/* /var/www/weather-app.hugo-vanhoutte.dev/
          # Remove the empty dist folder
          sudo rm -rf /var/www/weather-app.hugo-vanhoutte.dev/*

    - name: Deploy via SFTP
      uses: appleboy/scp-action@v0.1.5
      with:
        debug: true
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "dist/"
        target: "/var/www/weather-app.hugo-vanhoutte.dev/"
        
    - name: Execute SSH commands to move content
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          # Move contents of dist to target directory
          mv /var/www/weather-app.hugo-vanhoutte.dev/dist/* /var/www/weather-app.hugo-vanhoutte.dev/
          # Remove the empty dist folder
          sudo rm -rf /var/www/weather-app.***/dist/

